Dockerize
montrosesoftware/databrary-be pull request #2
Opened 2024-04-10 12:04 UTC by zakrzaq

- Docker
- docker-compose
- local, prod env

2024-04-11 05:32 UTC, zakrzaq commented on docker-compose.prod.yml
> +    image: postgres:16.2-alpine
Will remove. This was more of a place holder more ten anything else. I would not dream of running prod db in docker

2024-04-11 05:50 UTC, zakrzaq commented on databrary/settings/alone.py
> +        "ENGINE": "django.db.backends.sqlite3",
I left option to run BE repo standalone. I will replace with local instance of postgres for consistency

2024-04-11 05:50 UTC, zakrzaq commented on databrary/settings/base.py
> +        "ENGINE": ("django.db.backends.postgresql"),
We don't

2024-04-11 08:07 UTC, OlhaHn requested changes

2024-04-11 08:07 UTC, OlhaHn commented on databrary/settings/base.py
> +        "ENGINE": "django.db.backends.postgresql",
What about the rest? "Name", "User" etc

2024-04-11 08:09 UTC, zakrzaq commented on databrary/settings/base.py
> +        "ENGINE": "django.db.backends.postgresql",
removed

2024-04-12 08:22 UTC, OlhaHn approved these changes

2024-04-12 08:22 UTC, merged